/* Generated by scripts/gen_fp_fixed.py. Do not edit manually.
 * p = 2^191 * 3^117 - 1.
 * The generator verifies the schedules using integer exponents. */
#include "include/fp.h"

/* Exponent: 0x56dc0b83150865aa1e731a62339f3d42d1b551af0a95a65fffffffffffffffffffffffffffffffffffffffffffffff; width 5; 371S + 84M.
 * Each table index and loop bound is fixed, independent of the input. */
void fp_exp3div4(digit_t *out, const digit_t *a) {
  fp_t powers[16], a2, r;
  fp_copy(powers[0], a);
  fp_sqr(a2, a);
  fp_mul(powers[1], powers[0], a2);
  fp_mul(powers[2], powers[1], a2);
  fp_mul(powers[3], powers[2], a2);
  fp_mul(powers[4], powers[3], a2);
  fp_mul(powers[5], powers[4], a2);
  fp_mul(powers[6], powers[5], a2);
  fp_mul(powers[7], powers[6], a2);
  fp_mul(powers[8], powers[7], a2);
  fp_mul(powers[9], powers[8], a2);
  fp_mul(powers[10], powers[9], a2);
  fp_mul(powers[11], powers[10], a2);
  fp_mul(powers[12], powers[11], a2);
  fp_mul(powers[13], powers[12], a2);
  fp_mul(powers[14], powers[13], a2);
  fp_mul(powers[15], powers[14], a2);
  fp_copy(r, powers[10]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[5]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[3]);
  for (int i = 0; i < 11; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[11]);
  for (int i = 0; i < 7; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[1]);
  for (int i = 0; i < 8; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[10]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[0]);
  for (int i = 0; i < 9; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[12]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[6]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[2]);
  for (int i = 0; i < 8; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[3]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[1]);
  for (int i = 0; i < 7; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[6]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[1]);
  for (int i = 0; i < 8; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[8]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[9]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[9]);
  for (int i = 0; i < 3; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[3]);
  for (int i = 0; i < 6; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[2]);
  for (int i = 0; i < 8; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[5]);
  for (int i = 0; i < 6; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[8]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[5]);
  for (int i = 0; i < 6; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[10]);
  for (int i = 0; i < 6; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[8]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[10]);
  for (int i = 0; i < 3; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[3]);
  for (int i = 0; i < 9; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[10]);
  for (int i = 0; i < 7; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[10]);
  for (int i = 0; i < 3; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[2]);
  for (int i = 0; i < 7; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[12]);
  for (int i = 0; i < 6; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[15]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  fp_copy(out, r);
}

/* Exponent: 0x56dc0b83150865aa1e731a62339f3d42d1b551af0a95a6600000000000000000000000000000000000000000000000; width 5; 371S + 44M.
 * Each table index and loop bound is fixed, independent of the input. */
void fp_sqrt(digit_t *a) {
  fp_t powers[13], a2, r;
  fp_copy(powers[0], a);
  fp_sqr(a2, a);
  fp_mul(powers[1], powers[0], a2);
  fp_mul(powers[2], powers[1], a2);
  fp_mul(powers[3], powers[2], a2);
  fp_mul(powers[4], powers[3], a2);
  fp_mul(powers[5], powers[4], a2);
  fp_mul(powers[6], powers[5], a2);
  fp_mul(powers[7], powers[6], a2);
  fp_mul(powers[8], powers[7], a2);
  fp_mul(powers[9], powers[8], a2);
  fp_mul(powers[10], powers[9], a2);
  fp_mul(powers[11], powers[10], a2);
  fp_mul(powers[12], powers[11], a2);
  fp_copy(r, powers[10]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[5]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[3]);
  for (int i = 0; i < 11; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[11]);
  for (int i = 0; i < 7; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[1]);
  for (int i = 0; i < 8; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[10]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[0]);
  for (int i = 0; i < 9; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[12]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[6]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[2]);
  for (int i = 0; i < 8; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[3]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[1]);
  for (int i = 0; i < 7; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[6]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[1]);
  for (int i = 0; i < 8; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[8]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[9]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[9]);
  for (int i = 0; i < 3; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[3]);
  for (int i = 0; i < 6; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[2]);
  for (int i = 0; i < 8; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[5]);
  for (int i = 0; i < 6; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[8]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[5]);
  for (int i = 0; i < 6; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[10]);
  for (int i = 0; i < 6; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[8]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[10]);
  for (int i = 0; i < 3; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[3]);
  for (int i = 0; i < 9; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[10]);
  for (int i = 0; i < 7; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[10]);
  for (int i = 0; i < 3; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[2]);
  for (int i = 0; i < 7; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[12]);
  fp_sqr(r, r);
  fp_mul(r, r, powers[0]);
  for (int i = 0; i < 189; i++)
    fp_sqr(r, r);
  fp_copy(a, r);
}
