/* SPDX-License-Identifier: Apache-2.0
 * Generated by scripts/gen_fp_backend.py; do not edit.
 * Primitive generator by Mike Scott, TII (see scripts/vendor/LICENSE.modarith).
 */
#include "include/fp.h"
#include <encoded_sizes.h>

//Automatically generated modular arithmetic C code
//Command line : python monty.py 64 44708211844379432333883683285115313680357589701767069253607483419177907126271
//Python Script by Mike Scott (Technology Innovation Institute, UAE, 2025)

#include <stdio.h>
#include <stdint.h>

#define sspint int64_t
#define spint uint64_t
#define dpint __uint128_t
#define sdpint __int128_t
#define Wordlength 64
#define Nlimbs 5
#define Radix 52
#define Nbits 255
#define Nbytes 32

#define MONTGOMERY
//propagate carries
static spint inline prop(spint *n) {
	int i;
	spint mask=((spint)1<<52u)-(spint)1;
	sspint carry=(sspint)n[0];
	carry>>=52u;
	n[0]&=mask;
	for (i=1;i<4;i++) {
		carry+=(sspint)n[i];
		n[i] = (spint)carry & mask;
		carry>>=52u;
	}
	n[4]+=(spint)carry;
	return -((n[4]>>1)>>62u);
}

//propagate carries and add p if negative, propagate carries again
static inline spint flatten(spint *n) {
	spint carry=prop(n);
	n[0]-=(spint)1u&carry;
	n[2]+=((spint)0x3fa83c8000000u)&carry;
	n[3]+=((spint)0xe5fca7ecc14ecu)&carry;
	n[4]+=((spint)0x62d7f37f9815u)&carry;
	(void)prop(n);
	return (carry&1);
}

//Montgomery final subtract
static inline spint modfsb(spint *n) {
	n[0]+=(spint)1u;
	n[2]-=(spint)0x3fa83c8000000u;
	n[3]-=(spint)0xe5fca7ecc14ecu;
	n[4]-=(spint)0x62d7f37f9815u;
	return flatten(n);
}

// Addition modulo 2p with fused carry propagation; exact aliasing allowed.
static inline void modadd(const spint *a, const spint *b, spint *n) {
    spint s0 = a[0] + b[0];
    spint s1 = a[1] + b[1];
    spint s2 = a[2] + b[2];
    spint s3 = a[3] + b[3];
    spint s4 = a[4] + b[4];
    // Normalize a+b-2p while computing it. Keep the signed top limb.
    spint t0 = s0 + UINT64_C(0x2);
    spint t1 = s1 + (spint)((sspint)t0 >> 52);
    spint t2 = s2 - UINT64_C(0x7f50790000000) + (spint)((sspint)t1 >> 52);
    spint t3 = s3 - UINT64_C(0xcbf94fd9829d8) + (spint)((sspint)t2 >> 52);
    spint t4 = s4 - UINT64_C(0xc5afe6ff302b) + (spint)((sspint)t3 >> 52);
    spint m = (spint)((sspint)t4 >> 63);
    // Add back 2p if negative; propagate each carry directly into the next limb.
    spint z0 = (t0 & UINT64_C(0xfffffffffffff)) - (UINT64_C(0x2) & m);
    n[0] = z0 & UINT64_C(0xfffffffffffff);
    spint z1 = (t1 & UINT64_C(0xfffffffffffff)) + (spint)((sspint)z0 >> 52);
    n[1] = z1 & UINT64_C(0xfffffffffffff);
    spint z2 = (t2 & UINT64_C(0xfffffffffffff)) + (UINT64_C(0x7f50790000000) & m) + (spint)((sspint)z1 >> 52);
    n[2] = z2 & UINT64_C(0xfffffffffffff);
    spint z3 = (t3 & UINT64_C(0xfffffffffffff)) + (UINT64_C(0xcbf94fd9829d8) & m) + (spint)((sspint)z2 >> 52);
    n[3] = z3 & UINT64_C(0xfffffffffffff);
    spint z4 = t4 + (UINT64_C(0xc5afe6ff302b) & m) + (spint)((sspint)z3 >> 52);
    n[4] = z4 & UINT64_C(0xfffffffffffff);
}

//Modular subtraction - reduce less than 2p
static inline void modsub(const spint *a,const spint *b,spint *n) {
	spint carry;
	n[0]=a[0]-b[0];
	n[1]=a[1]-b[1];
	n[2]=a[2]-b[2];
	n[3]=a[3]-b[3];
	n[4]=a[4]-b[4];
	carry=prop(n);
	n[0]-=(spint)2u&carry;
	n[2]+=((spint)0x7f50790000000u)&carry;
	n[3]+=((spint)0x1cbf94fd9829d8u)&carry;
	n[4]+=((spint)0xc5afe6ff302au)&carry;
	(void)prop(n);
}

//Modular negation
static inline void modneg(const spint *b,spint *n) {
	spint carry;
	n[0]=(spint)0-b[0];
	n[1]=(spint)0-b[1];
	n[2]=(spint)0-b[2];
	n[3]=(spint)0-b[3];
	n[4]=(spint)0-b[4];
	carry=prop(n);
	n[0]-=(spint)2u&carry;
	n[2]+=((spint)0x7f50790000000u)&carry;
	n[3]+=((spint)0x1cbf94fd9829d8u)&carry;
	n[4]+=((spint)0xc5afe6ff302au)&carry;
	(void)prop(n);
}

// Overflow limit   = 340282366920938463463374607431768211456
// maximum possible = 125166380999214016859814290019076
// Modular multiplication, c=a*b mod 2p
static inline void modmul(const spint *a,const spint *b,spint *c) {
	dpint t=0;
	spint p2=0x3fa83c8000000u;
	spint p3=0xe5fca7ecc14ecu;
	spint p4=0x62d7f37f9815u;
	spint q=((spint)1<<52u); // q is unsaturated radix 
	spint mask=(spint)(q-(spint)1);
	t+=(dpint)a[0]*b[0]; spint v0=((spint)t & mask); t>>=52;
	t+=(dpint)a[0]*b[1]; t+=(dpint)a[1]*b[0]; spint v1=((spint)t & mask);  t>>=52;
	t+=(dpint)a[0]*b[2]; t+=(dpint)a[1]*b[1]; t+=(dpint)a[2]*b[0]; t+=(dpint)v0*(dpint)p2;  spint v2=((spint)t & mask);  t>>=52;
	t+=(dpint)a[0]*b[3]; t+=(dpint)a[1]*b[2]; t+=(dpint)a[2]*b[1]; t+=(dpint)a[3]*b[0]; t+=(dpint)v0*(dpint)p3;  t+=(dpint)v1*(dpint)p2;  spint v3=((spint)t & mask);  t>>=52;
	t+=(dpint)a[0]*b[4]; t+=(dpint)a[1]*b[3]; t+=(dpint)a[2]*b[2]; t+=(dpint)a[3]*b[1]; t+=(dpint)a[4]*b[0]; t+=(dpint)v0*(dpint)p4;  t+=(dpint)v1*(dpint)p3;  t+=(dpint)v2*(dpint)p2;  spint v4=((spint)t & mask);  t>>=52;
	t+=(dpint)a[1]*b[4]; t+=(dpint)a[2]*b[3]; t+=(dpint)a[3]*b[2]; t+=(dpint)a[4]*b[1]; t+=(dpint)v1*(dpint)p4;  t+=(dpint)v2*(dpint)p3;  t+=(dpint)v3*(dpint)p2;  c[0]=((spint)t & mask);  t>>=52;
	t+=(dpint)a[2]*b[4]; t+=(dpint)a[3]*b[3]; t+=(dpint)a[4]*b[2]; t+=(dpint)v2*(dpint)p4;  t+=(dpint)v3*(dpint)p3;  t+=(dpint)v4*(dpint)p2;  c[1]=((spint)t & mask);  t>>=52;
	t+=(dpint)a[3]*b[4]; t+=(dpint)a[4]*b[3]; t+=(dpint)v3*(dpint)p4;  t+=(dpint)v4*(dpint)p3;  c[2]=((spint)t & mask);  t>>=52;
	t+=(dpint)a[4]*b[4]; t+=(dpint)v4*(dpint)p4;  c[3]=((spint)t & mask);  t>>=52;
	c[4] = (spint)t;
}

// Modular squaring, c=a*a  mod 2p
static inline void modsqr(const spint *a,spint *c) {
	dpint tot;
	dpint t=0;
	spint p2=0x3fa83c8000000u;
	spint p3=0xe5fca7ecc14ecu;
	spint p4=0x62d7f37f9815u;
	spint q=((spint)1<<52u); // q is unsaturated radix 
	spint mask=(spint)(q-(spint)1);
	tot=(dpint)a[0]*a[0]; t=tot; spint v0=((spint)t & mask); t>>=52;
	tot=(dpint)a[0]*a[1]; tot*=2; t+=tot;  spint v1=((spint)t & mask); t>>=52;
	tot=(dpint)a[0]*a[2]; tot*=2; tot+=(dpint)a[1]*a[1]; t+=tot;  t+=(dpint)v0*p2;  spint v2=((spint)t & mask); t>>=52;
	tot=(dpint)a[0]*a[3]; tot+=(dpint)a[1]*a[2]; tot*=2; t+=tot;  t+=(dpint)v0*p3;  t+=(dpint)v1*p2;  spint v3=((spint)t & mask); t>>=52;
	tot=(dpint)a[0]*a[4]; tot+=(dpint)a[1]*a[3]; tot*=2; tot+=(dpint)a[2]*a[2]; t+=tot;  t+=(dpint)v0*p4;  t+=(dpint)v1*p3;  t+=(dpint)v2*p2;  spint v4=((spint)t & mask); t>>=52;
	tot=(dpint)a[1]*a[4]; tot+=(dpint)a[2]*a[3]; tot*=2; t+=tot;  t+=(dpint)v1*p4;  t+=(dpint)v2*p3;  t+=(dpint)v3*p2;  c[0]=((spint)t & mask);  t>>=52;
	tot=(dpint)a[2]*a[4]; tot*=2; tot+=(dpint)a[3]*a[3]; t+=tot;  t+=(dpint)v2*p4;  t+=(dpint)v3*p3;  t+=(dpint)v4*p2;  c[1]=((spint)t & mask);  t>>=52;
	tot=(dpint)a[3]*a[4]; tot*=2; t+=tot;  t+=(dpint)v3*p4;  t+=(dpint)v4*p3;  c[2]=((spint)t & mask);  t>>=52;
	tot=(dpint)a[4]*a[4]; t+=tot;  t+=(dpint)v4*p4;  c[3]=((spint)t & mask);  t>>=52;
	c[4] = (spint)t;
}

//Convert m to n-residue form, n=nres(m) 
static inline void nres(const spint *m,spint *n) {
	const spint c[5]={0x60b899325e6bdu,0xe5d0b8bfb72f3u,0x49fb511b0613bu,0xddb30a711826cu,0x3fc977bbdc72u};
	modmul(m,c,n);
}

//Convert n back to normal form, m=redc(n) 
static inline void redc(const spint *n,spint *m) {
	int i;
	spint c[5];
	c[0]=1;
	for (i=1;i<5;i++) {
		c[i]=0;
	}
	modmul(n,c,m);
	(void)modfsb(m);
}

static const fp_t FP_ONE = {UINT64_C(0x29), UINT64_C(0x0), UINT64_C(0xce0e4f8000000), UINT64_C(0x2a891b150a629), UINT64_C(0x2b6a0090a47e)};
static const fp_t FP_THREE_INV = {UINT64_C(0x5555555555563), UINT64_C(0x5555555555555), UINT64_C(0x44af6fd555555), UINT64_C(0x6383090703763), UINT64_C(0xe78aadae17f)};
static const fp_t FP_LEGACY_R = {UINT64_C(0x360b899325e6b), UINT64_C(0xbe5d0b8bfb72f), UINT64_C(0xb8586639b0613), UINT64_C(0xf8b879176e926), UINT64_C(0x544c0d536958)};
static const fp_t FP_BYTE_BASE = {UINT64_C(0x2970), UINT64_C(0x0), UINT64_C(0x34b5080000000), UINT64_C(0xea919d75d0272), UINT64_C(0x2b8608d1f495)};

#include "../fp_backend.inc"
