
set(SOURCE_FILES_SQISIGN2DPUSH_GENERIC_REF
    ${SQISIGN2DPUSH_LVLX_DIR}/doublepath.c
    ${SQISIGN2DPUSH_LVLX_DIR}/sign.c
    ${SQISIGN2DPUSH_LVLX_DIR}/keygen.c
    ${SQISIGN2DPUSH_LVLX_DIR}/toolbox.c
    ${SQISIGN2DPUSH_LVLX_DIR}/verify.c
)

add_library(${LIB_SQISIGN2DPUSH_${SVARIANT_UPPER}} ${SOURCE_FILES_SQISIGN2DPUSH_GENERIC_REF})
target_include_directories(${LIB_SQISIGN2DPUSH_${SVARIANT_UPPER}} PRIVATE common ${INC_PUBLIC} ${INC_INTBIG} ${INC_PRECOMP_${SVARIANT_UPPER}} ${INC_QUATERNION} ${INC_KLPT} ${INC_GF_${SVARIANT_UPPER}} ${INC_EC} ${INC_ID2ISO} ${INC_SQISIGN2DPUSH} ${INC_HD} ${INC_COMMON})
target_compile_definitions(${LIB_SQISIGN2DPUSH_${SVARIANT_UPPER}} PUBLIC SQISIGN_VARIANT=${SVARIANT_LOWER})
target_compile_options(${LIB_SQISIGN2DPUSH_${SVARIANT_UPPER}} PRIVATE ${C_OPT_FLAGS})

add_subdirectory(test)
