/* SPDX-License-Identifier: Apache-2.0
 * Generated by scripts/gen_fp_backend.py; do not edit.
 * Primitive generator by Mike Scott, TII (see scripts/vendor/LICENSE.modarith).
 */
#include "include/fp.h"
#include <encoded_sizes.h>

//Automatically generated modular arithmetic C code
//Command line : python monty.py 64 208889193927789181811378045775908259540756399513340350743437518349996463111022862407923846760766449240840050049023
//Python Script by Mike Scott (Technology Innovation Institute, UAE, 2025)

#include <stdio.h>
#include <stdint.h>

#define sspint int64_t
#define spint uint64_t
#define dpint __uint128_t
#define sdpint __int128_t
#define Wordlength 64
#define Nlimbs 7
#define Radix 55
#define Nbits 377
#define Nbytes 48

#define MONTGOMERY
//propagate carries
static spint inline prop(spint *n) {
	int i;
	spint mask=((spint)1<<55u)-(spint)1;
	sspint carry=(sspint)n[0];
	carry>>=55u;
	n[0]&=mask;
	for (i=1;i<6;i++) {
		carry+=(sspint)n[i];
		n[i] = (spint)carry & mask;
		carry>>=55u;
	}
	n[6]+=(spint)carry;
	return -((n[6]>>1)>>62u);
}

//propagate carries and add p if negative, propagate carries again
static inline spint flatten(spint *n) {
	spint carry=prop(n);
	n[0]-=(spint)1u&carry;
	n[3]+=((spint)0x6152b4cc000000u)&carry;
	n[4]+=((spint)0x67cf50b46d546bu)&carry;
	n[5]+=((spint)0x32d50f398d3119u)&carry;
	n[6]+=((spint)0x56dc0b831508u)&carry;
	(void)prop(n);
	return (carry&1);
}

//Montgomery final subtract
static inline spint modfsb(spint *n) {
	n[0]+=(spint)1u;
	n[3]-=(spint)0x6152b4cc000000u;
	n[4]-=(spint)0x67cf50b46d546bu;
	n[5]-=(spint)0x32d50f398d3119u;
	n[6]-=(spint)0x56dc0b831508u;
	return flatten(n);
}

// Addition modulo 2p with fused carry propagation; exact aliasing allowed.
static inline void modadd(const spint *a, const spint *b, spint *n) {
    spint s0 = a[0] + b[0];
    spint s1 = a[1] + b[1];
    spint s2 = a[2] + b[2];
    spint s3 = a[3] + b[3];
    spint s4 = a[4] + b[4];
    spint s5 = a[5] + b[5];
    spint s6 = a[6] + b[6];
    // Normalize a+b-2p while computing it. Keep the signed top limb.
    spint t0 = s0 + UINT64_C(0x2);
    spint t1 = s1 + (spint)((sspint)t0 >> 55);
    spint t2 = s2 + (spint)((sspint)t1 >> 55);
    spint t3 = s3 - UINT64_C(0x42a56998000000) + (spint)((sspint)t2 >> 55);
    spint t4 = s4 - UINT64_C(0x4f9ea168daa8d7) + (spint)((sspint)t3 >> 55);
    spint t5 = s5 - UINT64_C(0x65aa1e731a6233) + (spint)((sspint)t4 >> 55);
    spint t6 = s6 - UINT64_C(0xadb817062a10) + (spint)((sspint)t5 >> 55);
    spint m = (spint)((sspint)t6 >> 63);
    // Add back 2p if negative; propagate each carry directly into the next limb.
    spint z0 = (t0 & UINT64_C(0x7fffffffffffff)) - (UINT64_C(0x2) & m);
    n[0] = z0 & UINT64_C(0x7fffffffffffff);
    spint z1 = (t1 & UINT64_C(0x7fffffffffffff)) + (spint)((sspint)z0 >> 55);
    n[1] = z1 & UINT64_C(0x7fffffffffffff);
    spint z2 = (t2 & UINT64_C(0x7fffffffffffff)) + (spint)((sspint)z1 >> 55);
    n[2] = z2 & UINT64_C(0x7fffffffffffff);
    spint z3 = (t3 & UINT64_C(0x7fffffffffffff)) + (UINT64_C(0x42a56998000000) & m) + (spint)((sspint)z2 >> 55);
    n[3] = z3 & UINT64_C(0x7fffffffffffff);
    spint z4 = (t4 & UINT64_C(0x7fffffffffffff)) + (UINT64_C(0x4f9ea168daa8d7) & m) + (spint)((sspint)z3 >> 55);
    n[4] = z4 & UINT64_C(0x7fffffffffffff);
    spint z5 = (t5 & UINT64_C(0x7fffffffffffff)) + (UINT64_C(0x65aa1e731a6233) & m) + (spint)((sspint)z4 >> 55);
    n[5] = z5 & UINT64_C(0x7fffffffffffff);
    spint z6 = t6 + (UINT64_C(0xadb817062a10) & m) + (spint)((sspint)z5 >> 55);
    n[6] = z6 & UINT64_C(0x7fffffffffffff);
}

//Modular subtraction - reduce less than 2p
static inline void modsub(const spint *a,const spint *b,spint *n) {
	spint carry;
	n[0]=a[0]-b[0];
	n[1]=a[1]-b[1];
	n[2]=a[2]-b[2];
	n[3]=a[3]-b[3];
	n[4]=a[4]-b[4];
	n[5]=a[5]-b[5];
	n[6]=a[6]-b[6];
	carry=prop(n);
	n[0]-=(spint)2u&carry;
	n[3]+=((spint)0xc2a56998000000u)&carry;
	n[4]+=((spint)0xcf9ea168daa8d6u)&carry;
	n[5]+=((spint)0x65aa1e731a6232u)&carry;
	n[6]+=((spint)0xadb817062a10u)&carry;
	(void)prop(n);
}

//Modular negation
static inline void modneg(const spint *b,spint *n) {
	spint carry;
	n[0]=(spint)0-b[0];
	n[1]=(spint)0-b[1];
	n[2]=(spint)0-b[2];
	n[3]=(spint)0-b[3];
	n[4]=(spint)0-b[4];
	n[5]=(spint)0-b[5];
	n[6]=(spint)0-b[6];
	carry=prop(n);
	n[0]-=(spint)2u&carry;
	n[3]+=((spint)0xc2a56998000000u)&carry;
	n[4]+=((spint)0xcf9ea168daa8d6u)&carry;
	n[5]+=((spint)0x65aa1e731a6232u)&carry;
	n[6]+=((spint)0xadb817062a10u)&carry;
	(void)prop(n);
}

// Overflow limit   = 340282366920938463463374607431768211456
// maximum possible = 11645190654339247299842095871845755
// Modular multiplication, c=a*b mod 2p
static inline void modmul(const spint *a,const spint *b,spint *c) {
	dpint t=0;
	spint p3=0x6152b4cc000000u;
	spint p4=0x67cf50b46d546bu;
	spint p5=0x32d50f398d3119u;
	spint p6=0x56dc0b831508u;
	spint q=((spint)1<<55u); // q is unsaturated radix 
	spint mask=(spint)(q-(spint)1);
	t+=(dpint)a[0]*b[0]; spint v0=((spint)t & mask); t>>=55;
	t+=(dpint)a[0]*b[1]; t+=(dpint)a[1]*b[0]; spint v1=((spint)t & mask);  t>>=55;
	t+=(dpint)a[0]*b[2]; t+=(dpint)a[1]*b[1]; t+=(dpint)a[2]*b[0]; spint v2=((spint)t & mask);  t>>=55;
	t+=(dpint)a[0]*b[3]; t+=(dpint)a[1]*b[2]; t+=(dpint)a[2]*b[1]; t+=(dpint)a[3]*b[0]; t+=(dpint)v0*(dpint)p3;  spint v3=((spint)t & mask);  t>>=55;
	t+=(dpint)a[0]*b[4]; t+=(dpint)a[1]*b[3]; t+=(dpint)a[2]*b[2]; t+=(dpint)a[3]*b[1]; t+=(dpint)a[4]*b[0]; t+=(dpint)v0*(dpint)p4;  t+=(dpint)v1*(dpint)p3;  spint v4=((spint)t & mask);  t>>=55;
	t+=(dpint)a[0]*b[5]; t+=(dpint)a[1]*b[4]; t+=(dpint)a[2]*b[3]; t+=(dpint)a[3]*b[2]; t+=(dpint)a[4]*b[1]; t+=(dpint)a[5]*b[0]; t+=(dpint)v0*(dpint)p5;  t+=(dpint)v1*(dpint)p4;  t+=(dpint)v2*(dpint)p3;  spint v5=((spint)t & mask);  t>>=55;
	t+=(dpint)a[0]*b[6]; t+=(dpint)a[1]*b[5]; t+=(dpint)a[2]*b[4]; t+=(dpint)a[3]*b[3]; t+=(dpint)a[4]*b[2]; t+=(dpint)a[5]*b[1]; t+=(dpint)a[6]*b[0]; t+=(dpint)v0*(dpint)p6;  t+=(dpint)v1*(dpint)p5;  t+=(dpint)v2*(dpint)p4;  t+=(dpint)v3*(dpint)p3;  spint v6=((spint)t & mask);  t>>=55;
	t+=(dpint)a[1]*b[6]; t+=(dpint)a[2]*b[5]; t+=(dpint)a[3]*b[4]; t+=(dpint)a[4]*b[3]; t+=(dpint)a[5]*b[2]; t+=(dpint)a[6]*b[1]; t+=(dpint)v1*(dpint)p6;  t+=(dpint)v2*(dpint)p5;  t+=(dpint)v3*(dpint)p4;  t+=(dpint)v4*(dpint)p3;  c[0]=((spint)t & mask);  t>>=55;
	t+=(dpint)a[2]*b[6]; t+=(dpint)a[3]*b[5]; t+=(dpint)a[4]*b[4]; t+=(dpint)a[5]*b[3]; t+=(dpint)a[6]*b[2]; t+=(dpint)v2*(dpint)p6;  t+=(dpint)v3*(dpint)p5;  t+=(dpint)v4*(dpint)p4;  t+=(dpint)v5*(dpint)p3;  c[1]=((spint)t & mask);  t>>=55;
	t+=(dpint)a[3]*b[6]; t+=(dpint)a[4]*b[5]; t+=(dpint)a[5]*b[4]; t+=(dpint)a[6]*b[3]; t+=(dpint)v3*(dpint)p6;  t+=(dpint)v4*(dpint)p5;  t+=(dpint)v5*(dpint)p4;  t+=(dpint)v6*(dpint)p3;  c[2]=((spint)t & mask);  t>>=55;
	t+=(dpint)a[4]*b[6]; t+=(dpint)a[5]*b[5]; t+=(dpint)a[6]*b[4]; t+=(dpint)v4*(dpint)p6;  t+=(dpint)v5*(dpint)p5;  t+=(dpint)v6*(dpint)p4;  c[3]=((spint)t & mask);  t>>=55;
	t+=(dpint)a[5]*b[6]; t+=(dpint)a[6]*b[5]; t+=(dpint)v5*(dpint)p6;  t+=(dpint)v6*(dpint)p5;  c[4]=((spint)t & mask);  t>>=55;
	t+=(dpint)a[6]*b[6]; t+=(dpint)v6*(dpint)p6;  c[5]=((spint)t & mask);  t>>=55;
	c[6] = (spint)t;
}

// Modular squaring, c=a*a  mod 2p
static inline void modsqr(const spint *a,spint *c) {
	dpint tot;
	dpint t=0;
	spint p3=0x6152b4cc000000u;
	spint p4=0x67cf50b46d546bu;
	spint p5=0x32d50f398d3119u;
	spint p6=0x56dc0b831508u;
	spint q=((spint)1<<55u); // q is unsaturated radix 
	spint mask=(spint)(q-(spint)1);
	tot=(dpint)a[0]*a[0]; t=tot; spint v0=((spint)t & mask); t>>=55;
	tot=(dpint)a[0]*a[1]; tot*=2; t+=tot;  spint v1=((spint)t & mask); t>>=55;
	tot=(dpint)a[0]*a[2]; tot*=2; tot+=(dpint)a[1]*a[1]; t+=tot;  spint v2=((spint)t & mask); t>>=55;
	tot=(dpint)a[0]*a[3]; tot+=(dpint)a[1]*a[2]; tot*=2; t+=tot;  t+=(dpint)v0*p3;  spint v3=((spint)t & mask); t>>=55;
	tot=(dpint)a[0]*a[4]; tot+=(dpint)a[1]*a[3]; tot*=2; tot+=(dpint)a[2]*a[2]; t+=tot;  t+=(dpint)v0*p4;  t+=(dpint)v1*p3;  spint v4=((spint)t & mask); t>>=55;
	tot=(dpint)a[0]*a[5]; tot+=(dpint)a[1]*a[4]; tot+=(dpint)a[2]*a[3]; tot*=2; t+=tot;  t+=(dpint)v0*p5;  t+=(dpint)v1*p4;  t+=(dpint)v2*p3;  spint v5=((spint)t & mask); t>>=55;
	tot=(dpint)a[0]*a[6]; tot+=(dpint)a[1]*a[5]; tot+=(dpint)a[2]*a[4]; tot*=2; tot+=(dpint)a[3]*a[3]; t+=tot;  t+=(dpint)v0*p6;  t+=(dpint)v1*p5;  t+=(dpint)v2*p4;  t+=(dpint)v3*p3;  spint v6=((spint)t & mask); t>>=55;
	tot=(dpint)a[1]*a[6]; tot+=(dpint)a[2]*a[5]; tot+=(dpint)a[3]*a[4]; tot*=2; t+=tot;  t+=(dpint)v1*p6;  t+=(dpint)v2*p5;  t+=(dpint)v3*p4;  t+=(dpint)v4*p3;  c[0]=((spint)t & mask);  t>>=55;
	tot=(dpint)a[2]*a[6]; tot+=(dpint)a[3]*a[5]; tot*=2; tot+=(dpint)a[4]*a[4]; t+=tot;  t+=(dpint)v2*p6;  t+=(dpint)v3*p5;  t+=(dpint)v4*p4;  t+=(dpint)v5*p3;  c[1]=((spint)t & mask);  t>>=55;
	tot=(dpint)a[3]*a[6]; tot+=(dpint)a[4]*a[5]; tot*=2; t+=tot;  t+=(dpint)v3*p6;  t+=(dpint)v4*p5;  t+=(dpint)v5*p4;  t+=(dpint)v6*p3;  c[2]=((spint)t & mask);  t>>=55;
	tot=(dpint)a[4]*a[6]; tot*=2; tot+=(dpint)a[5]*a[5]; t+=tot;  t+=(dpint)v4*p6;  t+=(dpint)v5*p5;  t+=(dpint)v6*p4;  c[3]=((spint)t & mask);  t>>=55;
	tot=(dpint)a[5]*a[6]; tot*=2; t+=tot;  t+=(dpint)v5*p6;  t+=(dpint)v6*p5;  c[4]=((spint)t & mask);  t>>=55;
	tot=(dpint)a[6]*a[6]; t+=tot;  t+=(dpint)v6*p6;  c[5]=((spint)t & mask);  t>>=55;
	c[6] = (spint)t;
}

//Convert m to n-residue form, n=nres(m) 
static inline void nres(const spint *m,spint *n) {
	const spint c[7]={0x384c74e0e7248eu,0x63dbeb9f3fbc13u,0x221b867a354892u,0x5dd208eff12afau,0x457752df848cefu,0x2744478a9e8fa3u,0x4f0d5466aaa1u};
	modmul(m,c,n);
}

//Convert n back to normal form, m=redc(n) 
static inline void redc(const spint *n,spint *m) {
	int i;
	spint c[7];
	c[0]=1;
	for (i=1;i<7;i++) {
		c[i]=0;
	}
	modmul(n,c,m);
	(void)modfsb(m);
}

static const fp_t FP_ONE = {UINT64_C(0x179), UINT64_C(0x0), UINT64_C(0x0), UINT64_C(0x2d33bf94000000), UINT64_C(0x1fb2264afead4e), UINT64_C(0x243c943f12b0fd), UINT64_C(0x15f30bf606a2)};
static const fp_t FP_THREE_INV = {UINT64_C(0x2aaaaaaaaaab28), UINT64_C(0x55555555555555), UINT64_C(0x2aaaaaaaaaaaaa), UINT64_C(0x5a2cd175555555), UINT64_C(0x2d2b27aa7955e8), UINT64_C(0x725b367d8aa0b2), UINT64_C(0x244507d30938)};
static const fp_t FP_LEGACY_R = {UINT64_C(0x5c263a70739247), UINT64_C(0x31edf5cf9fde09), UINT64_C(0x110dc33d1aa449), UINT64_C(0x6ee90477f8957d), UINT64_C(0x62bba96fc24677), UINT64_C(0x53a223c54f47d1), UINT64_C(0x2786aa335550)};
static const fp_t FP_BYTE_BASE = {UINT64_C(0x17940), UINT64_C(0x0), UINT64_C(0x0), UINT64_C(0x5f126100000000), UINT64_C(0x3e521de3583369), UINT64_C(0x75070af64b6cb), UINT64_C(0x3c091541602f)};

#include "../fp_backend.inc"
