/* SPDX-License-Identifier: Apache-2.0
 * Generated by scripts/gen_fp_backend.py; do not edit.
 * Primitive generator by Mike Scott, TII (see scripts/vendor/LICENSE.modarith).
 */
#include "include/fp.h"
#include <encoded_sizes.h>

//Automatically generated modular arithmetic C code
//Command line : python monty.py 64 3997648412643818725327228144055742021781333111111183625009884266810282721893113926851368553903149314384359621333170299481651520498656019027028722705235967
//Python Script by Mike Scott (Technology Innovation Institute, UAE, 2025)

#include <stdio.h>
#include <stdint.h>

#define sspint int64_t
#define spint uint64_t
#define dpint __uint128_t
#define sdpint __int128_t
#define Wordlength 64
#define Nlimbs 9
#define Radix 57
#define Nbits 511
#define Nbytes 64

#define MONTGOMERY
//propagate carries
static spint inline prop(spint *n) {
	int i;
	spint mask=((spint)1<<57u)-(spint)1;
	sspint carry=(sspint)n[0];
	carry>>=57u;
	n[0]&=mask;
	for (i=1;i<8;i++) {
		carry+=(sspint)n[i];
		n[i] = (spint)carry & mask;
		carry>>=57u;
	}
	n[8]+=(spint)carry;
	return -((n[8]>>1)>>62u);
}

//propagate carries and add p if negative, propagate carries again
static inline spint flatten(spint *n) {
	spint carry=prop(n);
	n[0]-=(spint)1u&carry;
	n[4]+=((spint)0xcec98800000000u)&carry;
	n[5]+=((spint)0x94b4da62377c85u)&carry;
	n[6]+=((spint)0x82e362870715u)&carry;
	n[7]+=((spint)0xbe4694b88a96dcu)&carry;
	n[8]+=((spint)0x4c54193130bb66u)&carry;
	(void)prop(n);
	return (carry&1);
}

//Montgomery final subtract
static inline spint modfsb(spint *n) {
	n[0]+=(spint)1u;
	n[4]-=(spint)0xcec98800000000u;
	n[5]-=(spint)0x94b4da62377c85u;
	n[6]-=(spint)0x82e362870715u;
	n[7]-=(spint)0xbe4694b88a96dcu;
	n[8]-=(spint)0x4c54193130bb66u;
	return flatten(n);
}

// Addition modulo 2p with fused carry propagation; exact aliasing allowed.
static inline void modadd(const spint *a, const spint *b, spint *n) {
    spint s0 = a[0] + b[0];
    spint s1 = a[1] + b[1];
    spint s2 = a[2] + b[2];
    spint s3 = a[3] + b[3];
    spint s4 = a[4] + b[4];
    spint s5 = a[5] + b[5];
    spint s6 = a[6] + b[6];
    spint s7 = a[7] + b[7];
    spint s8 = a[8] + b[8];
    // Normalize a+b-2p while computing it. Keep the signed top limb.
    spint t0 = s0 + UINT64_C(0x2);
    spint t1 = s1 + (spint)((sspint)t0 >> 57);
    spint t2 = s2 + (spint)((sspint)t1 >> 57);
    spint t3 = s3 + (spint)((sspint)t2 >> 57);
    spint t4 = s4 - UINT64_C(0x19d931000000000) + (spint)((sspint)t3 >> 57);
    spint t5 = s5 - UINT64_C(0x12969b4c46ef90a) + (spint)((sspint)t4 >> 57);
    spint t6 = s6 - UINT64_C(0x105c6c50e0e2a) + (spint)((sspint)t5 >> 57);
    spint t7 = s7 - UINT64_C(0x17c8d2971152db8) + (spint)((sspint)t6 >> 57);
    spint t8 = s8 - UINT64_C(0x98a832626176cc) + (spint)((sspint)t7 >> 57);
    spint m = (spint)((sspint)t8 >> 63);
    // Add back 2p if negative; propagate each carry directly into the next limb.
    spint z0 = (t0 & UINT64_C(0x1ffffffffffffff)) - (UINT64_C(0x2) & m);
    n[0] = z0 & UINT64_C(0x1ffffffffffffff);
    spint z1 = (t1 & UINT64_C(0x1ffffffffffffff)) + (spint)((sspint)z0 >> 57);
    n[1] = z1 & UINT64_C(0x1ffffffffffffff);
    spint z2 = (t2 & UINT64_C(0x1ffffffffffffff)) + (spint)((sspint)z1 >> 57);
    n[2] = z2 & UINT64_C(0x1ffffffffffffff);
    spint z3 = (t3 & UINT64_C(0x1ffffffffffffff)) + (spint)((sspint)z2 >> 57);
    n[3] = z3 & UINT64_C(0x1ffffffffffffff);
    spint z4 = (t4 & UINT64_C(0x1ffffffffffffff)) + (UINT64_C(0x19d931000000000) & m) + (spint)((sspint)z3 >> 57);
    n[4] = z4 & UINT64_C(0x1ffffffffffffff);
    spint z5 = (t5 & UINT64_C(0x1ffffffffffffff)) + (UINT64_C(0x12969b4c46ef90a) & m) + (spint)((sspint)z4 >> 57);
    n[5] = z5 & UINT64_C(0x1ffffffffffffff);
    spint z6 = (t6 & UINT64_C(0x1ffffffffffffff)) + (UINT64_C(0x105c6c50e0e2a) & m) + (spint)((sspint)z5 >> 57);
    n[6] = z6 & UINT64_C(0x1ffffffffffffff);
    spint z7 = (t7 & UINT64_C(0x1ffffffffffffff)) + (UINT64_C(0x17c8d2971152db8) & m) + (spint)((sspint)z6 >> 57);
    n[7] = z7 & UINT64_C(0x1ffffffffffffff);
    spint z8 = t8 + (UINT64_C(0x98a832626176cc) & m) + (spint)((sspint)z7 >> 57);
    n[8] = z8 & UINT64_C(0x1ffffffffffffff);
}

//Modular subtraction - reduce less than 2p
static inline void modsub(const spint *a,const spint *b,spint *n) {
	spint carry;
	n[0]=a[0]-b[0];
	n[1]=a[1]-b[1];
	n[2]=a[2]-b[2];
	n[3]=a[3]-b[3];
	n[4]=a[4]-b[4];
	n[5]=a[5]-b[5];
	n[6]=a[6]-b[6];
	n[7]=a[7]-b[7];
	n[8]=a[8]-b[8];
	carry=prop(n);
	n[0]-=(spint)2u&carry;
	n[4]+=((spint)0x19d931000000000u)&carry;
	n[5]+=((spint)0x12969b4c46ef90au)&carry;
	n[6]+=((spint)0x105c6c50e0e2au)&carry;
	n[7]+=((spint)0x17c8d2971152db8u)&carry;
	n[8]+=((spint)0x98a832626176ccu)&carry;
	(void)prop(n);
}

//Modular negation
static inline void modneg(const spint *b,spint *n) {
	spint carry;
	n[0]=(spint)0-b[0];
	n[1]=(spint)0-b[1];
	n[2]=(spint)0-b[2];
	n[3]=(spint)0-b[3];
	n[4]=(spint)0-b[4];
	n[5]=(spint)0-b[5];
	n[6]=(spint)0-b[6];
	n[7]=(spint)0-b[7];
	n[8]=(spint)0-b[8];
	carry=prop(n);
	n[0]-=(spint)2u&carry;
	n[4]+=((spint)0x19d931000000000u)&carry;
	n[5]+=((spint)0x12969b4c46ef90au)&carry;
	n[6]+=((spint)0x105c6c50e0e2au)&carry;
	n[7]+=((spint)0x17c8d2971152db8u)&carry;
	n[8]+=((spint)0x98a832626176ccu)&carry;
	(void)prop(n);
}

// Overflow limit   = 340282366920938463463374607431768211456
// maximum possible = 212178716016149914099826974253263405
// Modular multiplication, c=a*b mod 2p
static inline void modmul(const spint *a,const spint *b,spint *c) {
	dpint t=0;
	spint p4=0xcec98800000000u;
	spint p5=0x94b4da62377c85u;
	spint p6=0x82e362870715u;
	spint p7=0xbe4694b88a96dcu;
	spint p8=0x4c54193130bb66u;
	spint q=((spint)1<<57u); // q is unsaturated radix 
	spint mask=(spint)(q-(spint)1);
	t+=(dpint)a[0]*b[0]; spint v0=((spint)t & mask); t>>=57;
	t+=(dpint)a[0]*b[1]; t+=(dpint)a[1]*b[0]; spint v1=((spint)t & mask);  t>>=57;
	t+=(dpint)a[0]*b[2]; t+=(dpint)a[1]*b[1]; t+=(dpint)a[2]*b[0]; spint v2=((spint)t & mask);  t>>=57;
	t+=(dpint)a[0]*b[3]; t+=(dpint)a[1]*b[2]; t+=(dpint)a[2]*b[1]; t+=(dpint)a[3]*b[0]; spint v3=((spint)t & mask);  t>>=57;
	t+=(dpint)a[0]*b[4]; t+=(dpint)a[1]*b[3]; t+=(dpint)a[2]*b[2]; t+=(dpint)a[3]*b[1]; t+=(dpint)a[4]*b[0]; t+=(dpint)v0*(dpint)p4;  spint v4=((spint)t & mask);  t>>=57;
	t+=(dpint)a[0]*b[5]; t+=(dpint)a[1]*b[4]; t+=(dpint)a[2]*b[3]; t+=(dpint)a[3]*b[2]; t+=(dpint)a[4]*b[1]; t+=(dpint)a[5]*b[0]; t+=(dpint)v0*(dpint)p5;  t+=(dpint)v1*(dpint)p4;  spint v5=((spint)t & mask);  t>>=57;
	t+=(dpint)a[0]*b[6]; t+=(dpint)a[1]*b[5]; t+=(dpint)a[2]*b[4]; t+=(dpint)a[3]*b[3]; t+=(dpint)a[4]*b[2]; t+=(dpint)a[5]*b[1]; t+=(dpint)a[6]*b[0]; t+=(dpint)v0*(dpint)p6;  t+=(dpint)v1*(dpint)p5;  t+=(dpint)v2*(dpint)p4;  spint v6=((spint)t & mask);  t>>=57;
	t+=(dpint)a[0]*b[7]; t+=(dpint)a[1]*b[6]; t+=(dpint)a[2]*b[5]; t+=(dpint)a[3]*b[4]; t+=(dpint)a[4]*b[3]; t+=(dpint)a[5]*b[2]; t+=(dpint)a[6]*b[1]; t+=(dpint)a[7]*b[0]; t+=(dpint)v0*(dpint)p7;  t+=(dpint)v1*(dpint)p6;  t+=(dpint)v2*(dpint)p5;  t+=(dpint)v3*(dpint)p4;  spint v7=((spint)t & mask);  t>>=57;
	t+=(dpint)a[0]*b[8]; t+=(dpint)a[1]*b[7]; t+=(dpint)a[2]*b[6]; t+=(dpint)a[3]*b[5]; t+=(dpint)a[4]*b[4]; t+=(dpint)a[5]*b[3]; t+=(dpint)a[6]*b[2]; t+=(dpint)a[7]*b[1]; t+=(dpint)a[8]*b[0]; t+=(dpint)v0*(dpint)p8;  t+=(dpint)v1*(dpint)p7;  t+=(dpint)v2*(dpint)p6;  t+=(dpint)v3*(dpint)p5;  t+=(dpint)v4*(dpint)p4;  spint v8=((spint)t & mask);  t>>=57;
	t+=(dpint)a[1]*b[8]; t+=(dpint)a[2]*b[7]; t+=(dpint)a[3]*b[6]; t+=(dpint)a[4]*b[5]; t+=(dpint)a[5]*b[4]; t+=(dpint)a[6]*b[3]; t+=(dpint)a[7]*b[2]; t+=(dpint)a[8]*b[1]; t+=(dpint)v1*(dpint)p8;  t+=(dpint)v2*(dpint)p7;  t+=(dpint)v3*(dpint)p6;  t+=(dpint)v4*(dpint)p5;  t+=(dpint)v5*(dpint)p4;  c[0]=((spint)t & mask);  t>>=57;
	t+=(dpint)a[2]*b[8]; t+=(dpint)a[3]*b[7]; t+=(dpint)a[4]*b[6]; t+=(dpint)a[5]*b[5]; t+=(dpint)a[6]*b[4]; t+=(dpint)a[7]*b[3]; t+=(dpint)a[8]*b[2]; t+=(dpint)v2*(dpint)p8;  t+=(dpint)v3*(dpint)p7;  t+=(dpint)v4*(dpint)p6;  t+=(dpint)v5*(dpint)p5;  t+=(dpint)v6*(dpint)p4;  c[1]=((spint)t & mask);  t>>=57;
	t+=(dpint)a[3]*b[8]; t+=(dpint)a[4]*b[7]; t+=(dpint)a[5]*b[6]; t+=(dpint)a[6]*b[5]; t+=(dpint)a[7]*b[4]; t+=(dpint)a[8]*b[3]; t+=(dpint)v3*(dpint)p8;  t+=(dpint)v4*(dpint)p7;  t+=(dpint)v5*(dpint)p6;  t+=(dpint)v6*(dpint)p5;  t+=(dpint)v7*(dpint)p4;  c[2]=((spint)t & mask);  t>>=57;
	t+=(dpint)a[4]*b[8]; t+=(dpint)a[5]*b[7]; t+=(dpint)a[6]*b[6]; t+=(dpint)a[7]*b[5]; t+=(dpint)a[8]*b[4]; t+=(dpint)v4*(dpint)p8;  t+=(dpint)v5*(dpint)p7;  t+=(dpint)v6*(dpint)p6;  t+=(dpint)v7*(dpint)p5;  t+=(dpint)v8*(dpint)p4;  c[3]=((spint)t & mask);  t>>=57;
	t+=(dpint)a[5]*b[8]; t+=(dpint)a[6]*b[7]; t+=(dpint)a[7]*b[6]; t+=(dpint)a[8]*b[5]; t+=(dpint)v5*(dpint)p8;  t+=(dpint)v6*(dpint)p7;  t+=(dpint)v7*(dpint)p6;  t+=(dpint)v8*(dpint)p5;  c[4]=((spint)t & mask);  t>>=57;
	t+=(dpint)a[6]*b[8]; t+=(dpint)a[7]*b[7]; t+=(dpint)a[8]*b[6]; t+=(dpint)v6*(dpint)p8;  t+=(dpint)v7*(dpint)p7;  t+=(dpint)v8*(dpint)p6;  c[5]=((spint)t & mask);  t>>=57;
	t+=(dpint)a[7]*b[8]; t+=(dpint)a[8]*b[7]; t+=(dpint)v7*(dpint)p8;  t+=(dpint)v8*(dpint)p7;  c[6]=((spint)t & mask);  t>>=57;
	t+=(dpint)a[8]*b[8]; t+=(dpint)v8*(dpint)p8;  c[7]=((spint)t & mask);  t>>=57;
	c[8] = (spint)t;
}

// Modular squaring, c=a*a  mod 2p
static inline void modsqr(const spint *a,spint *c) {
	dpint tot;
	dpint t=0;
	spint p4=0xcec98800000000u;
	spint p5=0x94b4da62377c85u;
	spint p6=0x82e362870715u;
	spint p7=0xbe4694b88a96dcu;
	spint p8=0x4c54193130bb66u;
	spint q=((spint)1<<57u); // q is unsaturated radix 
	spint mask=(spint)(q-(spint)1);
	tot=(dpint)a[0]*a[0]; t=tot; spint v0=((spint)t & mask); t>>=57;
	tot=(dpint)a[0]*a[1]; tot*=2; t+=tot;  spint v1=((spint)t & mask); t>>=57;
	tot=(dpint)a[0]*a[2]; tot*=2; tot+=(dpint)a[1]*a[1]; t+=tot;  spint v2=((spint)t & mask); t>>=57;
	tot=(dpint)a[0]*a[3]; tot+=(dpint)a[1]*a[2]; tot*=2; t+=tot;  spint v3=((spint)t & mask); t>>=57;
	tot=(dpint)a[0]*a[4]; tot+=(dpint)a[1]*a[3]; tot*=2; tot+=(dpint)a[2]*a[2]; t+=tot;  t+=(dpint)v0*p4;  spint v4=((spint)t & mask); t>>=57;
	tot=(dpint)a[0]*a[5]; tot+=(dpint)a[1]*a[4]; tot+=(dpint)a[2]*a[3]; tot*=2; t+=tot;  t+=(dpint)v0*p5;  t+=(dpint)v1*p4;  spint v5=((spint)t & mask); t>>=57;
	tot=(dpint)a[0]*a[6]; tot+=(dpint)a[1]*a[5]; tot+=(dpint)a[2]*a[4]; tot*=2; tot+=(dpint)a[3]*a[3]; t+=tot;  t+=(dpint)v0*p6;  t+=(dpint)v1*p5;  t+=(dpint)v2*p4;  spint v6=((spint)t & mask); t>>=57;
	tot=(dpint)a[0]*a[7]; tot+=(dpint)a[1]*a[6]; tot+=(dpint)a[2]*a[5]; tot+=(dpint)a[3]*a[4]; tot*=2; t+=tot;  t+=(dpint)v0*p7;  t+=(dpint)v1*p6;  t+=(dpint)v2*p5;  t+=(dpint)v3*p4;  spint v7=((spint)t & mask); t>>=57;
	tot=(dpint)a[0]*a[8]; tot+=(dpint)a[1]*a[7]; tot+=(dpint)a[2]*a[6]; tot+=(dpint)a[3]*a[5]; tot*=2; tot+=(dpint)a[4]*a[4]; t+=tot;  t+=(dpint)v0*p8;  t+=(dpint)v1*p7;  t+=(dpint)v2*p6;  t+=(dpint)v3*p5;  t+=(dpint)v4*p4;  spint v8=((spint)t & mask); t>>=57;
	tot=(dpint)a[1]*a[8]; tot+=(dpint)a[2]*a[7]; tot+=(dpint)a[3]*a[6]; tot+=(dpint)a[4]*a[5]; tot*=2; t+=tot;  t+=(dpint)v1*p8;  t+=(dpint)v2*p7;  t+=(dpint)v3*p6;  t+=(dpint)v4*p5;  t+=(dpint)v5*p4;  c[0]=((spint)t & mask);  t>>=57;
	tot=(dpint)a[2]*a[8]; tot+=(dpint)a[3]*a[7]; tot+=(dpint)a[4]*a[6]; tot*=2; tot+=(dpint)a[5]*a[5]; t+=tot;  t+=(dpint)v2*p8;  t+=(dpint)v3*p7;  t+=(dpint)v4*p6;  t+=(dpint)v5*p5;  t+=(dpint)v6*p4;  c[1]=((spint)t & mask);  t>>=57;
	tot=(dpint)a[3]*a[8]; tot+=(dpint)a[4]*a[7]; tot+=(dpint)a[5]*a[6]; tot*=2; t+=tot;  t+=(dpint)v3*p8;  t+=(dpint)v4*p7;  t+=(dpint)v5*p6;  t+=(dpint)v6*p5;  t+=(dpint)v7*p4;  c[2]=((spint)t & mask);  t>>=57;
	tot=(dpint)a[4]*a[8]; tot+=(dpint)a[5]*a[7]; tot*=2; tot+=(dpint)a[6]*a[6]; t+=tot;  t+=(dpint)v4*p8;  t+=(dpint)v5*p7;  t+=(dpint)v6*p6;  t+=(dpint)v7*p5;  t+=(dpint)v8*p4;  c[3]=((spint)t & mask);  t>>=57;
	tot=(dpint)a[5]*a[8]; tot+=(dpint)a[6]*a[7]; tot*=2; t+=tot;  t+=(dpint)v5*p8;  t+=(dpint)v6*p7;  t+=(dpint)v7*p6;  t+=(dpint)v8*p5;  c[4]=((spint)t & mask);  t>>=57;
	tot=(dpint)a[6]*a[8]; tot*=2; tot+=(dpint)a[7]*a[7]; t+=tot;  t+=(dpint)v6*p8;  t+=(dpint)v7*p7;  t+=(dpint)v8*p6;  c[5]=((spint)t & mask);  t>>=57;
	tot=(dpint)a[7]*a[8]; tot*=2; t+=tot;  t+=(dpint)v7*p8;  t+=(dpint)v8*p7;  c[6]=((spint)t & mask);  t>>=57;
	tot=(dpint)a[8]*a[8]; t+=tot;  t+=(dpint)v8*p8;  c[7]=((spint)t & mask);  t>>=57;
	c[8] = (spint)t;
}

//Convert m to n-residue form, n=nres(m) 
static inline void nres(const spint *m,spint *n) {
	const spint c[9]={0x176907ebbf1acbcu,0x75bf2f98de0398u,0x15dec2fa18bbf73u,0x1c52d39d843d50fu,0xc91d590c6213a7u,0xf72fce2f5f6098u,0x1072d755b50ad45u,0x17c826e1c2cc4d3u,0x456b55c749877au};
	modmul(m,c,n);
}

//Convert n back to normal form, m=redc(n) 
static inline void redc(const spint *n,spint *m) {
	int i;
	spint c[9];
	c[0]=1;
	for (i=1;i<9;i++) {
		c[i]=0;
	}
	modmul(n,c,m);
	(void)modfsb(m);
}

static const fp_t FP_ONE = {UINT64_C(0x6), UINT64_C(0x0), UINT64_C(0x0), UINT64_C(0x0), UINT64_C(0x12746d000000000), UINT64_C(0x83c2e1b2b314df), UINT64_C(0x1fceeabb0d5d580), UINT64_C(0x18a5883acc076d7), UINT64_C(0x360768d8db9b99)};
static const fp_t FP_THREE_INV = {UINT64_C(0xaaaaaaaaaaaaac), UINT64_C(0x155555555555555), UINT64_C(0xaaaaaaaaaaaaaa), UINT64_C(0x155555555555555), UINT64_C(0x196f34aaaaaaaaa), UINT64_C(0x139b9877d0b59f8), UINT64_C(0x1ff517b7ca14be3), UINT64_C(0x1acf739b49c8c2f), UINT64_C(0x44e533be69b0cc)};
static const fp_t FP_LEGACY_R = {UINT64_C(0xbb483f5df8d65e), UINT64_C(0x13adf97cc6f01cc), UINT64_C(0x1aef617d0c5dfb9), UINT64_C(0x1e2969cec21ea87), UINT64_C(0x648eac863109d3), UINT64_C(0x17b97e717afb04c), UINT64_C(0x18396baada856a2), UINT64_C(0xbe41370e166269), UINT64_C(0x22b5aae3a4c3bd)};
static const fp_t FP_BYTE_BASE = {UINT64_C(0x6b5), UINT64_C(0x0), UINT64_C(0x0), UINT64_C(0x0), UINT64_C(0x11252d800000000), UINT64_C(0x9f034b41d9d541), UINT64_C(0x9220ec2c5d7e34), UINT64_C(0x1d09c86467a2e72), UINT64_C(0xff30914271a63)};

#include "../fp_backend.inc"
