#!/usr/bin/env python3
"""Generate fixed Fp exponentiation schedules; no third-party dependencies.

Run from any directory. --check verifies the checked-in C files without writing.
All branch decisions and table indices are resolved here from public exponents.
"""

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PARAMETERS = {1: (131, 78), 3: (191, 117), 5: (263, 156)}
# Widths selected by measurement on the current 64-bit reference backend.
WIDTHS = {1: 4, 3: 5, 5: 5}
SQRT_WIDTHS = {1: 3, 3: 5, 5: 5}


def window_schedule(exponent, width):
    """Return (squarings, odd power) steps, proving the resulting exponent."""
    steps = []
    bit = exponent.bit_length() - 1
    pending = 0
    while bit >= 0:
        if not ((exponent >> bit) & 1):
            pending += 1
            bit -= 1
            continue
        low = max(0, bit - width + 1)
        while not ((exponent >> low) & 1):
            low += 1
        length = bit - low + 1
        power = (exponent >> low) & ((1 << length) - 1)
        steps.append((pending + length, power))
        pending = 0
        bit = low - 1
    if pending:
        steps.append((pending, 0))
    result = steps[0][1]
    for squares, power in steps[1:]:
        result = (result << squares) + power
    if result != exponent:
        raise ValueError("incorrect exponent schedule")
    return steps


def window_function(exponent, width, name, inplace=False):
    steps = window_schedule(exponent, width)
    size = max(power for _, power in steps) // 2 + 1
    squares = 1 + sum(count for count, _ in steps[1:])
    multiplies = size - 1 + sum(power != 0 for _, power in steps[1:])
    args = "digit_t *a" if inplace else "digit_t *out, const digit_t *a"
    lines = [
        f"/* Exponent: 0x{exponent:x}; width {width}; {squares}S + {multiplies}M.",
        " * Each table index and loop bound is fixed, independent of the input. */",
        f"void {name}({args}) {{",
        f"  fp_t powers[{size}], a2, r;",
        "  fp_copy(powers[0], a);",
        "  fp_sqr(a2, a);",
    ]
    for i in range(1, size):
        lines.append(f"  fp_mul(powers[{i}], powers[{i - 1}], a2);")
    lines.append(f"  fp_copy(r, powers[{steps[0][1] // 2}]);")
    for count, power in steps[1:]:
        if count == 1:
            lines.append("  fp_sqr(r, r);")
        else:
            lines += [f"  for (int i = 0; i < {count}; i++)", "    fp_sqr(r, r);"]
        if power:
            lines.append(f"  fp_mul(r, r, powers[{power // 2}]);")
    lines += [f"  fp_copy({'a' if inplace else 'out'}, r);", "}"]
    return "\n".join(lines)


def render(level):
    twos, threes = PARAMETERS[level]
    prime = (1 << twos) * 3**threes - 1
    parts = [
        "/* Generated by scripts/gen_fp_fixed.py. Do not edit manually.",
        f" * p = 2^{twos} * 3^{threes} - 1.",
        " * The generator verifies the schedules using integer exponents. */",
        '#include "include/fp.h"',
        "",
        window_function((prime - 3) // 4, WIDTHS[level], "fp_exp3div4"),
        "",
    ]
    parts.append(window_function((prime + 1) // 4, SQRT_WIDTHS[level],
                                 "fp_sqrt", inplace=True))
    return "\n".join(parts) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for level in PARAMETERS:
        path = ROOT / f"src/gf/ref/lvl{level}/fp_exp.c"
        content = render(level)
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"stale generated file: {path}")
        else:
            path.write_text(content)
        print(f"{'Checked' if args.check else 'Generated'} {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
