#!/usr/bin/env python3
"""Generate v2-style primitives for the 2DPush primes (no addchain dependency).

Vendored monty.py: mcarrickscott/modarith dcdd51a3f49af0462d7a50f3bbdf63588c9f0cc0.
Only the generator setup and primitive emitters are executed; its exponent,
benchmark and compiler drivers are not used. Fixed exponents use gen_fp_fixed.py.
"""
import argparse
import contextlib
import io
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
PARAMETERS = ((1, 131, 78, 52, 5, 4), (3, 191, 117, 55, 7, 6), (5, 263, 156, 57, 9, 8))


def generate_add(p, radix, limbs):
    """Fuse the sum, subtraction of 2p, and carry propagation.

    Represent 2p as (-2, q1, ...), with qi the radix digits of 2p+2.
    All input limbs are loaded before output stores, including for out == a/b.
    The signed intermediates lie strictly between -2B and 3B (B=2^radix),
    well inside int64_t. Arithmetic right shift is also used by monty.py.
    """
    mask = (1 << radix) - 1
    q = [(2*p + 2) >> (i*radix) & mask for i in range(limbs)]
    assert q[0] == 0 and radix <= 61 and 2*p < 1 << (limbs*radix)
    q[0] = -2
    literal = lambda v: f'UINT64_C(0x{v:x})'
    lines = [
        '// Addition modulo 2p with fused carry propagation; exact aliasing allowed.',
        'static inline void modadd(const spint *a, const spint *b, spint *n) {',
    ]
    for i in range(limbs):
        lines.append(f'    spint s{i} = a[{i}] + b[{i}];')
    lines.append('    // Normalize a+b-2p while computing it. Keep the signed top limb.')
    for i in range(limbs):
        term = f' + {literal(-q[i])}' if q[i] < 0 else f' - {literal(q[i])}' if q[i] else ''
        carry = f' + (spint)((sspint)t{i-1} >> {radix})' if i else ''
        lines.append(f'    spint t{i} = s{i}{term}{carry};')
    lines.append(f'    spint m = (spint)((sspint)t{limbs-1} >> 63);')
    lines.append('    // Add back 2p if negative; propagate each carry directly into the next limb.')
    for i in range(limbs):
        term = f' - ({literal(-q[i])} & m)' if q[i] < 0 else f' + ({literal(q[i])} & m)' if q[i] else ''
        carry = f' + (spint)((sspint)z{i-1} >> {radix})' if i else ''
        value = f'(t{i} & {literal(mask)})' if i < limbs-1 else f't{i}'
        lines.append(f'    spint z{i} = {value}{term}{carry};')
        lines.append(f'    n[{i}] = z{i} & {literal(mask)};')
    lines.append('}')
    return '\n'.join(lines) + '\n'


def generate(level, twos, threes, radix, limbs, words):
    p = (1 << twos) * 3**threes - 1
    source = (ROOT / 'scripts/vendor/monty.py').read_text()
    source = source[:source.index("import random\nwith open('test.c'")]
    start = source.index('cline="addchain search')
    end = source.index('# get number of bytes for export', start)
    source = source[:start] + source[end:]
    source = source.replace('fully_propagate=False', 'fully_propagate=True')
    source = source.replace('base=0\n', f'base={radix}\n')
    env = {}
    saved_argv = sys.argv
    try:
        sys.argv = ['monty.py', '64', str(p)]
        with contextlib.redirect_stdout(io.StringIO()):
            exec(compile(source, 'vendor/monty.py', 'exec'), env)
    finally:
        sys.argv = saved_argv
    assert env['N'] == limbs and env['R'] == 1 << (radix * limbs)
    assert env['R'] > 4 * p
    output = io.StringIO()
    with contextlib.redirect_stdout(output):
        sys.argv = ['monty.py', '64', str(p)]
        env['header']()
        sys.argv = saved_argv
        for name in ('prop', 'flat', 'modfsb', 'modadd', 'modsub', 'modneg', 'modmul', 'modsqr', 'nres', 'redc'):
            print(generate_add(p, radix, limbs) if name == 'modadd' else env[name](env['n']))
            if name in ('modmul', 'modsqr'):
                assert env['maxnum'] < 1 << 128
    assert env['maxnum'] < 1 << 128
    code = output.getvalue()
    # Keep generator helpers local; only the fp.h API is exported.
    code = re.sub(r'^(spint|void) (\w+\()', r'static inline \1 \2', code, flags=re.M)
    code = ('/* SPDX-License-Identifier: Apache-2.0\n'
            ' * Generated by scripts/gen_fp_backend.py; do not edit.\n'
            ' * Primitive generator by Mike Scott, TII (see scripts/vendor/LICENSE.modarith).\n'
            ' */\n#include "include/fp.h"\n#include <encoded_sizes.h>\n' + code)
    def const(name, val):
        return 'static const fp_t ' + name + ' = {' + ', '.join(
            f'UINT64_C(0x{(val >> (i*radix)) & ((1<<radix)-1):x})' for i in range(limbs)) + '};\n'
    R = 1 << (radix * limbs)
    code += const('FP_ONE', R % p)
    code += const('FP_THREE_INV', pow(3, -1, p) * R % p)
    code += const('FP_LEGACY_R', ((1 << (words * 64)) * R) % p)
    code += const('FP_BYTE_BASE', 256 * R % p)
    code += '\n#include "../fp_backend.inc"\n'
    return code


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for params in PARAMETERS:
        path = ROOT / f'src/gf/ref/lvl{params[0]}/fp_backend.c'
        code = generate(*params)
        if args.check:
            if not path.exists() or path.read_text() != code:
                raise SystemExit(f'{path}: stale generated code')
        else:
            path.write_text(code)
    print('Fp backend generation checked' if args.check else 'Fp backends generated')

if __name__ == '__main__':
    main()
