/* Generated by scripts/gen_fp_fixed.py. Do not edit manually.
 * p = 2^131 * 3^78 - 1.
 * The generator verifies the schedules using integer exponents. */
#include "include/fp.h"

/* Exponent: 0x18b5fcdfe605797f29fb3053b0fea0f1ffffffffffffffffffffffffffffffff; width 4; 252S + 64M.
 * Each table index and loop bound is fixed, independent of the input. */
void fp_exp3div4(digit_t *out, const digit_t *a) {
  fp_t powers[8], a2, r;
  fp_copy(powers[0], a);
  fp_sqr(a2, a);
  fp_mul(powers[1], powers[0], a2);
  fp_mul(powers[2], powers[1], a2);
  fp_mul(powers[3], powers[2], a2);
  fp_mul(powers[4], powers[3], a2);
  fp_mul(powers[5], powers[4], a2);
  fp_mul(powers[6], powers[5], a2);
  fp_mul(powers[7], powers[6], a2);
  fp_copy(r, powers[1]);
  for (int i = 0; i < 7; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[5]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[5]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[4]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[5]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 2; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[1]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[1]);
  for (int i = 0; i < 9; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[2]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 6; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[5]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[4]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[4]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[5]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[1]);
  for (int i = 0; i < 8; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[2]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[3]);
  for (int i = 0; i < 3; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[1]);
  for (int i = 0; i < 8; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 3; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[3]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[2]);
  for (int i = 0; i < 9; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 7; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[7]);
  fp_sqr(r, r);
  fp_mul(r, r, powers[0]);
  fp_copy(out, r);
}

/* Exponent: 0x18b5fcdfe605797f29fb3053b0fea0f200000000000000000000000000000000; width 3; 252S + 34M.
 * Each table index and loop bound is fixed, independent of the input. */
void fp_sqrt(digit_t *a) {
  fp_t powers[4], a2, r;
  fp_copy(powers[0], a);
  fp_sqr(a2, a);
  fp_mul(powers[1], powers[0], a2);
  fp_mul(powers[2], powers[1], a2);
  fp_mul(powers[3], powers[2], a2);
  fp_copy(r, powers[1]);
  for (int i = 0; i < 6; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[2]);
  for (int i = 0; i < 3; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[2]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[3]);
  for (int i = 0; i < 3; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[3]);
  fp_sqr(r, r);
  fp_mul(r, r, powers[0]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[1]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[3]);
  for (int i = 0; i < 3; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[3]);
  for (int i = 0; i < 2; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[1]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[1]);
  for (int i = 0; i < 9; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[2]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[3]);
  fp_sqr(r, r);
  fp_mul(r, r, powers[0]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[2]);
  for (int i = 0; i < 3; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[3]);
  for (int i = 0; i < 3; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[3]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[2]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[3]);
  for (int i = 0; i < 3; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[3]);
  for (int i = 0; i < 3; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[1]);
  for (int i = 0; i < 4; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[1]);
  for (int i = 0; i < 8; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[2]);
  for (int i = 0; i < 5; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[3]);
  for (int i = 0; i < 3; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[1]);
  for (int i = 0; i < 7; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[3]);
  for (int i = 0; i < 3; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[3]);
  for (int i = 0; i < 3; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[2]);
  for (int i = 0; i < 2; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[0]);
  for (int i = 0; i < 8; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[3]);
  fp_sqr(r, r);
  fp_mul(r, r, powers[0]);
  for (int i = 0; i < 3; i++)
    fp_sqr(r, r);
  fp_mul(r, r, powers[0]);
  for (int i = 0; i < 129; i++)
    fp_sqr(r, r);
  fp_copy(a, r);
}
